stages:
  - test

Test:
  image: python:3.7
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
  script:
    - python3 manage.py test
  tags:
    - test