stages:
  - test
  - test_functional
  - deploy

Test:
  image: python:3.7
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
  script:
    - python3 manage.py test lists
  tags:
    - test

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME ./manage.py makemigrations
    - heroku run --app $HEROKU_APPNAME ./manage.py migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST

TestFunctional:
  image: python:3.7
  stage: test_functional
  before_script:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - pip3 install -r requirements.txt
    - apt-get update -qq && apt-get install -y -qq unzip
    - apt-get install -y google-chrome-stable
    - apt-get install -y xvfb
    - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
  when: on_success
  script:
    - python manage.py test functional_tests